a = input('Please, set the first number. ')
a = int(a)
b = input('Please, set the second number. ')
b = int(b)
print('The sum of the values is ', a + b)
print('The difference between the values is ', a - b)
print('The product of the values is ', a * b)
